namespace: production

image:
  repository: guilhermefaleiros/url-shortener
  tag: latest

config:
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/url-shortener"
  REDIS_URL: "redis:6379"

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

replicaCount: 4
maxReplicas: 6

service:
  port: 80
  targetPort: 8080
  type: ClusterIP

livenessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 5

readinessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

hpa:
  cpuUtilization: 80
  memoryUtilization: 80