name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4.1.5

    - name: Log in to DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5.3.0
      with: 
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/url-shortener:${{ github.sha }}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out code
      uses: actions/checkout@v4.1.5

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.32.0'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.16.4'

    - name: Authenticate to kubernetes
      uses: azure/k8s-set-context@v4.0.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install url-shortener ./k8s \
          --namespace production \
          --set image.tag=${{ github.sha }}